name: Bump version

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Count the number of feature branches
          feature_branches=$(git branch --all | grep -c "release")

          # # Count the number of hotfix branches
          # hotfix_branches=$(git branch --all | grep -c "hotfix")

          # Print the values of the variables using echo
          echo "Feature branches: $feature_branches"
          # echo "Hotfix branches: $hotfix_branches"

          # # Update the version number using bump2version
          # bump2version --new-version "0.${feature_branches}.${hotfix_branches}"

          # # push tags to github and push final master version
          # git push --tags
          # git push

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.${feature_branches}.${hotfix_branches}
          release_name: Release v0.${feature_branches}.${hotfix_branches}
          body: |
            New release v0.${feature_branches}.${hotfix_branches} is now available.
