name: Bump version

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Conda
        run: |
          eval "$(conda shell.bash hook)"
          conda create --name bump_version_env python=3.8
          conda activate bump_version_env
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Give permissions to script
        run: chmod +x bump_version.sh
      - name: Run script in Conda environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda activate bump_version_env
          ./bump_version.sh
